### ISSUE TITLE
Contributing rules/guides

### ISSUE THREAD

**Issue by lleewwiiss** [tensorflow/custom-op#11]
I would like to contribute to this repo an example of how to create a cuda custom op, and then show how to add and use it in serving. Is there anything I should be aware of, contributing rules etc, before I create a PR? Also, Is the guide for serving something I should add here or elsewhere?

As a side note, there is currently no documentation on how to add and use cuda ops with serving, so my method may not be the ideal way to do it.

Thanks

**Comment by lleewwiiss** [comment]
I just noticed https://github.com/tensorflow/custom-op/pull/10, so this would only cover using customs ops gpu/cpu with serving. Is this the appropriate place to add this?

**Comment by martinwicke** [comment]
I think the best place to add that would be to tensorflow/serving actually, since I believe you would have to build a custom serving binary which includes the custom op. 

So assuming you have figured out how to do that, I think the most productive thing would be to add clear instructions (and maybe an example of the specific BUILD file changes needed) to tensorflow/serving?

@gautamvasudevan
@tensorflow/serving-members FYI

**Comment by lleewwiiss** [comment]
Okay, thank you I will submit a PR there and close this.
